spring.application.name=predict-be

# Server (Render)
server.port=${PORT:10000}

# PostgreSQL (Render - HARD CODED, FINAL)
spring.datasource.url=jdbc:postgresql://dpg-d5a3lvali9vc73avhnog-a.virginia-postgres.render.com:5432/cricpredict
spring.datasource.username=cricpredict_user
spring.datasource.password=KIW9ork34anJy9v2wrnFTiILbmJe7pDI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
